### PR TITLE
Add zoom functionality for linux and windows

### PR DESCRIPTION
**Pull request by kamiyaa**
Fixes https://github.com/celo-tools/celo-web-wallet/issues/80

### CODE REVIEW

**Comment by jmrossy** [comment]
@kamiyaa Thanks for the PR, looks good! I'm semi-offline atm for holidays but I'll test it in a few days and ship it with the next release.

**Comment by kamiyaa** [comment]
@jmrossy no problem! Happy holidays!

**Comment by jmrossy** [comment]
@kamiyaa I tested this today on MacOS and found it has no effect. I suspect this code needs to execute in the renderer process, not the main.js electron one. [See here](https://www.geeksforgeeks.org/zoom-functionality-in-electronjs/).

Also I'm not sure any changes are needed because zooming does work via `command + / -` or through the menu. Maybe it's different on Windows, is that where you tested?

Screen Shot 2021-12-28 at 18 08 24

**Comment by jmrossy** [comment]
Ah I think this answers my question. MacOS is different:
https://github.com/electron/electron/pull/17747/files#diff-675d2fdc497df732c76f0d75423e72331a9ffbb4d5c71d9ef792bd209b6edb70R350

**Comment by kamiyaa** [comment]
Oh I see. I was testing on Linux.
Also, I just found out you can scale electron apps via `--force-device-scale-factor=1.5` :eyes:

**Pull request merged**
